name: ci

on:
  push:
    branches: [main]
  pull_request:

jobs:
  ci:
    name: ci
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        version:
          - 1.64.0
          - 'nightly'

    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: setup
        run: |
          rustup set profile minimal
          rustup override set ${{ matrix.version }}

      - name: cache
        uses: Swatinem/rust-cache@v2.0.0

      - name: check
        if: matrix.version == '1.64.0'
        run: |
          rustup component add rustfmt
          rustup component add clippy
          cargo fmt --all -- --check
          cargo clippy

      - name: pre-test
        run: |
          chmod -r examples/translations/invalid/unreadable-dir
          chmod -r examples/translations/invalid/unreadable-file/messages.en.toml

      - name: test
        run: cargo test --all --doc

      - name: test ( all features )
        run: cargo test --all --all-features

      - name: test ( no default features )
        run: cargo test --all --no-default-features

      - name: post-test
        run: |
          chmod +r examples/translations/invalid/unreadable-dir
          chmod +r examples/translations/invalid/unreadable-file/messages.en.toml

      - name: build
        run: cargo build 

      - name: build ( all features )
        run: cargo build --all-features

      - name: build ( no default features )
        run: cargo build --no-default-features
